### PR TITLE
French: translate readme

### PR DESCRIPTION
**Pull request by AugustinMauroy**
# transe into French
Readme.md

### CODE REVIEW

**Comment by ezfe** [comment]
Merci beaucoup. J'ai fait des changements (sp.?) pour Minecraft 1.19. Je vais accepter le PR si tu peux faire les modifications.

S'il tu plait excuser mon français, je ne parle pas tres bien

**Comment by AugustinMauroy** [comment]
No problem, I'll do it for you.
I find your French correct.

**Comment by AugustinMauroy** [comment]
It's done.
I don't know how to trace Swift. If you know how to show me I'll translate the launcher stuff.

**Comment by ezfe** [comment]
I need to make some changes to allow for translation of the application, I can make the changes and then show you how to enter French translations. It should be easy.

I will let you know when I have a chance to do that

**Comment by AugustinMauroy** [comment]
@ezfe  Ok no problem you can merge the pr

**Pull request merged**
